repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-aws-credentials
        args:
        - --allow-missing-credentials
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_checkov
      args:
        - --args=--skip-path="examples/"
    - id: terraform_docs
      args:
      - --hook-config=--add-to-existing-file=true     # Boolean. true or false
      - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
